hl.on("hyprland.start", function()
    -- --- Launch Desktop ---
    hl.exec_cmd(barLaunch)
    hl.exec_cmd("mako")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("desktopctl time ~/Pictures/Wallpapers/gruvbox 900")
    hl.exec_cmd("hyprctl setcursor \"Capitaine Cursors\" 24")

    -- --- Launch Services ---
    hl.exec_cmd("sunshine")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("organizer.py -d")
    hl.exec_cmd("udiskie")
    hl.exec_cmd("wayclip.py daemon")
    hl.exec_cmd("medianotify")
    hl.exec_cmd("python3 -m http.server 8080 --bind 127.0.0.1 --directory ~/.config/startpage")
    hl.exec_cmd(portal)
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user import-environment QT_QPA_PLATFORMTHEME")
end)
