# See https://wiki.hypr.land/Configuring/Gestures
# workspace switching
gesture = 3, horizontal, workspace

# window actions
gesture = 3, up, fullscreen
gesture = 3, down, close

# floating toggle
gesture = 4, pinch, float

# move windows
gesture = 3, swipe, move
