terminal = "footclient"
fileManager = "thunar"
menu = "rofi -show drun"
browser = "librewolf"
scrPath = os.getenv("HOME") .. "/.config/hypr/scripts"
barLaunch = scrPath .. "/bar-launch.sh"
scratchpad = scrPath .. "/scratchpad.sh"
portal = scrPath .. "/portal-hypr.sh"
