# --- Primary Monitor ---
monitorv2 {
  output = HDMI-A-1
  mode = 1920x1080@74.97300
  position = 0x0
  scale = 1
  transform = 0
}
# --- Secondary Monitor ---
monitorv2 {
  output = HDMI-A-4
  mode = 1024x600@59.82100
  position = 0x1080
  scale = 1
  transform = 2
}
