# Foot Config
shell=zsh
term=xterm-256color
initial-window-mode=windowed

[main]
font=CaskaydiaCove NF:size=12
line-height=13
pad=6x6

[scrollback]
lines=5000

[cursor]
style=block

[colors-dark]
alpha=0.85
background=282828
foreground=ebdbb2

## Normal colors
regular0=3c3836 # bg1 (Black)
regular1=fb4934 # Red
regular2=b8bb26 # Green
regular3=fabd2f # Yellow
regular4=83a598 # Blue
regular5=d3869b # Purple
regular6=8ec07c # Aqua/Cyan
regular7=ebdbb2 # Light foreground

## Bright colors
bright0=504945 # bg2 (Bright Black)
bright1=cc241d # Bright Red
bright2=98971a # Bright Green
bright3=d79921 # Bright Yellow
bright4=458588 # Bright Blue
bright5=b16286 # Bright Magenta
bright6=ebdbb2 # Bright Cyan (fg)
bright7=fbf1c7 # Bright White

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
primary-paste=Shift+Insert
font-increase=Control+equal Control+plus
font-decrease=Control+minus
font-reset=Control+0
scrollback-up-page=Page_Up
scrollback-down-page=Page_Down
unicode-input=none
show-urls-launch=Control+Shift+u
