# =========================
# Core behavior
# =========================
auto_focus = false
mouse = false
autocomplete_limit = 0

# =========================
# Notifications
# =========================
[notifications]
enabled = true
duration = 0

[notifications.sound]
enabled = false

# =========================
# Typing indicator
# =========================
[typing_indicator]
send = true
receive = true

# =========================
# Global keybinds
# =========================
[keybinds]
focus_guilds_tree = "Ctrl+g"
focus_messages_list = "Ctrl+m"
focus_message_input = "Ctrl+i"

focus_previous = "Ctrl+h"
focus_next = "Ctrl+l"

quit = "Ctrl+q"
logout = "Ctrl+d"

# =========================
# Picker
# =========================
[keybinds.picker]
up = "k"
down = "j"
top = "gg"
bottom = "G"
select = "Enter"
cancel = "Esc"

# =========================
# Guild Tree
# =========================
[keybinds.guilds_tree]
up = "k"
down = "j"

top = "gg"
bottom = "G"

select_current = "l"

collapse_parent_node = "H"
move_to_parent_node = "h"

yank_id = "y"

# =========================
# Messages
# =========================
[keybinds.messages_list]
select_up = "k"
select_down = "j"

select_top = "gg"
select_bottom = "G"

scroll_up = "Ctrl+u"
scroll_down = "Ctrl+d"

scroll_top = "gg"
scroll_bottom = "G"

reply = "r"
reply_mention = "R"
select_reply = "s"

edit = "e"

delete = "x"
delete_confirm = "d"

open = "o"

yank_content = "y"
yank_url = "u"
yank_id = "i"

cancel = "Esc"

# =========================
# Message Input
# =========================
[keybinds.message_input]
send = "Enter"
cancel = "Esc"

tab_complete = "Tab"

paste = "Ctrl+v"

open_editor = "Ctrl+e"
open_file_picker = "Ctrl+\\"

# =========================
# Mentions
# =========================
[keybinds.mentions_list]
up = "k"
down = "j"
top = "gg"
bottom = "G"

# =========================
# Theme
# =========================
[theme.title]
normal_style = { attributes = "dim" }
active_style = { attributes = "bold" }

[theme.footer]
normal_style = { attributes = "dim" }
active_style = { attributes = "bold" }

[theme.border]
enabled = true
padding = [0, 0, 0, 0]
normal_style = { attributes = "dim" }
active_style = { attributes = "bold" }
normal_set = "plain"
active_set = "plain"

[theme.guilds_tree]
auto_expand_folders = true
graphics = true
graphics_color = "default"

[theme.messages_list]
reply_indicator = ">"
forwarded_indicator = "<"
message_style = {}
selected_message_style = { attributes = "reverse" }
mention_style = { attributes = "bold" }
url_style = { attributes = "underline" }

[theme.mentions_list]
min_width = 0
max_height = 0
